version: '2'
services:
  wiki_parser_python:
    build:
      context: ./../
      dockerfile: ./docker/python3.dockerfile
    image: python3:wiki_parser
    volumes:
      - datavolume:/app
    links:
      - wiki_parser_mongodb
    expose:
      - 5000

  wiki_parser_mongodb:
    build:
      context: ./../
      dockerfile: ./docker/mongodb.dockerfile
    image: mongodb:wiki_parser
    volumes:
      - /project/storages/wiki_gmaps_parser_mongodb:/data/db
    expose:
      - 27017

  nginx_wiki_parser:
    build:
      context: ./../
      dockerfile: ./docker/nginx.dockerfile
    image: nginx:wiki_parser
    volumes:
      - datavolume:/app
    ports:
      - 80:80
    links:
      - wiki_parser_python

volumes:
  datavolume: {}