# -*- coding: utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import collections


def GetHeader(Delimiter):
    DictHeader = {1:'InseeXls_CodeCommune',
                  2:'InseeXls_NameCommune',
                  3:'InseeXls_Population',
                  4:'Wiki_UrlInCommune',
                  5:'W_Pays',
                  6:'W_Region',
                  7:'W_Departement',
                  8:'W_Arrondissement',
                  9:'W_Canton',
                  10:'W_Intercommunalite',
                  11:'W_CodePostal',
                  12:'W_CodeCommune',
                  13:'W_Population',
                  14:'W_Densite',
                  15:'W_Cordommees',
                  16:'W_Altitude',
                  17:'W_Superficie',
                  18:'W_Name_ru',
                  19:'W_Name_uk',
                  20:'W_Name_en',
                  21:'W_Name_de',
                  22:'W_Name_pl',
                  23:'W_Name_es',
                  24:'W_Name_pt',
                  25:'W_Name_it',
                  26:'W_Name_nl',
                  27:'W_Name_da',
                  28:'W_Name_no',
                  29:'W_Name_sv',
                  30:'W_Name_cs',
                  31:'W_Name_ro',
                  32:'W_Name_bg',
                  33:'W_Name_hu',
                  34:'W_Name_sk',
                  35:'W_Name_sl',
                  36:'W_Name_sh',
                  37:'W_Name_hr',
                  38:'W_Url_ru',
                  39:'W_Url_uk',
                  40:'W_Url_en',
                  41:'W_Url_de',
                  42:'W_Url_pl',
                  43:'W_Url_es',
                  44:'W_Url_pt',
                  45:'W_Url_it',
                  46:'W_Url_nl',
                  47:'W_Url_da',
                  48:'W_Url_no',
                  49:'W_Url_sv',
                  50:'W_Url_cs',
                  51:'W_Url_ro',
                  52:'W_Url_bg',
                  53:'W_Url_hu',
                  54:'W_Url_sk',
                  55:'W_Url_sl',
                  56:'W_Url_sh',
                  57:'W_Url_hr',
                  58:'G_Coordinates_northeast_Lat_1',
                  59:'G_Coordinates_northeast_Lng_1',
                  60:'G_Coordinates_southwest_Lat_2',
                  61:'G_Coordinates_southwest_Lng_2',
                  62:'G_Coordinates_location_Lat_3',
                  63:'G_Coordinates_location_Lng_3',
                  64:'G_AddressComponents_locality_LongName',
                  65:'G_AddressComponents_locality_Types',
                  66:'G_AddressComponents_locality_ShortName',
                  67:'G_AddressComponents_localityLevel_2_LongName',
                  68:'G_AddressComponents_localityLevel_2_Types',
                  69:'G_AddressComponents_localityLevel_2_ShortName',
                  70:'G_AddressComponents_localityLevel_1_LongName',
                  71:'G_AddressComponents_localityLevel_1_Types',
                  72:'G_AddressComponents_localityLevel_1_ShortName',
                  73:'G_AddressComponents_localityCountry_LongName',
                  74:'G_AddressComponents_localityCountry_Types',
                  75:'G_AddressComponents_localityCountry_ShortName',
                  76:'G_FormatAddress',
                  77:'G_Types',
                  78:'G_PlaceId'


                  }


    DictHeader = collections.OrderedDict(sorted(DictHeader.items()))
    ListHeader = []
    for Header in DictHeader.values():
        ListHeader.append(Header)
    return Delimiter.join(ListHeader)


def GetHeader_2(Delimiter):
    DictHeader = {1:'InseeXls_CodeCommune',
                  2:'InseeXls_NameCommune',
                  3:'InseeXls_Population',
                  4:'Wiki_UrlInCommune',
                  5:'W_Pays',
                  6:'W_Region',
                  7:'W_Departement',
                  8:'W_Arrondissement',
                  9:'W_Canton',
                  10:'W_Intercommunalite',
                  11:'W_CodePostal',
                  12:'W_CodeCommune',
                  13:'W_Population',
                  14:'W_Densite',
                  15:'W_Cordommees',
                  16:'W_Altitude',
                  17:'W_Superficie',
                  18:'W_Name_ru',
                  19:'W_Name_uk',
                  20:'W_Name_en',
                  21:'W_Name_de',
                  22:'W_Name_pl',
                  23:'W_Name_es',
                  24:'W_Name_pt',
                  25:'W_Name_it',
                  26:'W_Name_nl',
                  27:'W_Name_da',
                  28:'W_Name_no',
                  29:'W_Name_sv',
                  30:'W_Name_cs',
                  31:'W_Name_ro',
                  32:'W_Name_bg',
                  33:'W_Name_hu',
                  34:'W_Name_sk',
                  35:'W_Name_sl',
                  36:'W_Name_sh',
                  37:'W_Name_hr',
                  38:'W_Url_ru',
                  39:'W_Url_uk',
                  40:'W_Url_en',
                  41:'W_Url_de',
                  42:'W_Url_pl',
                  43:'W_Url_es',
                  44:'W_Url_pt',
                  45:'W_Url_it',
                  46:'W_Url_nl',
                  47:'W_Url_da',
                  48:'W_Url_no',
                  49:'W_Url_sv',
                  50:'W_Url_cs',
                  51:'W_Url_ro',
                  52:'W_Url_bg',
                  53:'W_Url_hu',
                  54:'W_Url_sk',
                  55:'W_Url_sl',
                  56:'W_Url_sh',
                  57:'W_Url_hr',
                  58:'G_Coordinates_northeast_Lat_1',
                  59:'G_Coordinates_northeast_Lng_1',
                  60:'G_Coordinates_southwest_Lat_2',
                  61:'G_Coordinates_southwest_Lng_2',
                  62:'G_Coordinates_location_Lat_3',
                  63:'G_Coordinates_location_Lng_3',

                  64:'G_PlaceId',

                  65:'How_Get_GooglePlaceID',
                  66:'G_Locality_long_name',
                  67:'G_Locality_short_name',
                  68:'G_Locality_types',
                  69:'G_AdminLevel_1_long_name',
                  70:'G_AdminLevel_1_short_name',
                  71:'G_AdminLevel_1_types',
                  72:'G_AdminLevel_2_long_name',
                  73:'G_AdminLevel_2_short_name',
                  74:'G_AdminLevel_2_types',
                  75:'G_Country_long_name',
                  76:'G_Country_short_name',
                  77:'G_Country_types',
                  78:'G_postal_code_long_name',
                  79:'G_postal_code_short_name',
                  80:'G_postal_code_types',
                  81:'G_FormatAddress',
                  82:'G_Types',
                  83:'W_Cordommees_Convert',
                  84:'G_Name_ru',
                  85:'G_Name_uk',
                  86:'G_Name_en',
                  87:'F_Compare_InseeXls_CodeCommune_W_CodeCommune',
                  88:'F_Compare_InseeXls_NameCommune_Wiki_Url',
                  89:'F_Compare_InseeXls_NameCommune_G_Locality_long_name',
                  90:'Wiki_UrlInCommuneSnipet',
                  91:'Wiki_NameSnipet',
                  92:'Wiki_Old_UrlInCommune',
                  93:'Wiki_Old_NameSnipet',
                  94: 'ColResultInSnipet',
                  95: 'Wiki_NameSnipet_lower',
                  96: 'G_Locality_short_name_lower',
                  97: 'F_Compare_Wiki_NameSnipet_G_Locality_short_name_equally',
                  98: 'F_Compare_Wiki_NameSnipet_G_Locality_short_name_percentage',
                  99: 'F_Compare_Wiki_NameSnipet_G_Locality_short_name_percentage_more_or_equal_80',
                  100: 'W_Departement_status',
                  101: 'W_Arrondissement_status',
                  102: 'W_Canton_status'



                  }


    DictHeader = collections.OrderedDict(sorted(DictHeader.items()))
    ListHeader = []
    for Header in DictHeader.values():
        ListHeader.append(Header)
    return Delimiter.join(ListHeader)


def GetHeader_Canton(Delimiter):
    DictHeader = {1: 'I_Code_canton',
                  2: 'I_Region',
                  3: 'I_Dep',
                  4: 'I_Canton',
                  5: 'I_Typct',
                  6: 'I_Burcentral',
                  7: 'I_Tncc',
                  8: 'I_Artmaj',
                  9: 'I_Ncc',
                  10: 'I_Armin',
                  11: 'I_Nccent',
                  12: 'ColResultInSnipet',
                  13: 'Wiki_Url',
                  14: 'Wiki_Name_Snipet',
                  21: 'W_Pays',
                  22: 'W_Region',
                  23: 'W_Departement',
                  24: 'W_Arrondissement',
                  25: 'W_Bureau',
                  26: 'W_Code_Canton',
                  27: 'W_Creation',
                  28: 'W_Population',
                  29: 'W_Communes',
                  30: 'G_Types',
                  31: 'G_FormatAddress',
                  32: 'G_Locality_long_name',
                  33: 'G_Locality_short_name',
                  34: 'G_Locality_types',
                  35: 'G_AdminLevel_1_long_name',
                  36: 'G_AdminLevel_1_short_name',
                  37: 'G_AdminLevel_1_types',
                  38: 'G_AdminLevel_2_long_name',
                  39: 'G_AdminLevel_2_short_name',
                  40: 'G_AdminLevel_2_types',
                  41: 'G_Country_long_name',
                  42: 'G_Country_short_name',
                  43: 'G_Country_types',
                  44: 'G_postal_code_long_name',
                  45: 'G_postal_code_short_name',
                  46: 'G_postal_code_types',
                  47: 'G_Coordinates_northeast_Lat_1',
                  48: 'G_Coordinates_northeast_Lng_1',
                  49: 'G_Coordinates_southwest_Lat_2',
                  50: 'G_Coordinates_southwest_Lng_2',
                  51: 'G_Coordinates_location_Lat_3',
                  52: 'G_Coordinates_location_Lng_3',
                  53: 'W_Name_ru',
                  54: 'W_Name_uk',
                  55: 'W_Name_en',
                  56: 'W_Name_de',
                  57: 'W_Name_pl',
                  58: 'W_Name_es',
                  59: 'W_Name_pt',
                  60: 'W_Name_it',
                  61: 'W_Name_nl',
                  62: 'W_Name_da',
                  63: 'W_Name_no',
                  64: 'W_Name_sv',
                  65: 'W_Name_cs',
                  66: 'W_Name_ro',
                  67: 'W_Name_bg',
                  68: 'W_Name_hu',
                  69: 'W_Name_sk',
                  70: 'W_Name_sl',
                  71: 'W_Name_sh',
                  72: 'W_Name_hr',
                  73: 'W_Url_ru',
                  74: 'W_Url_uk',
                  75: 'W_Url_en',
                  76: 'W_Url_de',
                  77: 'W_Url_pl',
                  78: 'W_Url_es',
                  79: 'W_Url_pt',
                  80: 'W_Url_it',
                  81: 'W_Url_nl',
                  82: 'W_Url_da',
                  83: 'W_Url_no',
                  84: 'W_Url_sv',
                  85: 'W_Url_cs',
                  86: 'W_Url_ro',
                  87: 'W_Url_bg',
                  88: 'W_Url_hu',
                  89: 'W_Url_sk',
                  90: 'W_Url_sl',
                  91: 'W_Url_sh',
                  92: 'W_Url_hr',
                  }

    DictHeader = collections.OrderedDict(sorted(DictHeader.items()))
    ListHeader = []
    for Header in DictHeader.values():
        ListHeader.append(Header)
    return Delimiter.join(ListHeader)


def GetHeader_Arrondissements(Delimiter):
    DictHeader = {1: 'I_Code_Arrondissements',
                  2: 'I_Region',
                  3: 'I_Dep',
                  4: 'I_Ar',
                  5: 'I_Cheflieu',
                  6: 'I_Tncc',
                  7: 'I_Artmaj',
                  8: 'I_Ncc',
                  9: 'I_Armin',
                  10: 'I_Nccent',
                  11: 'ColResultInSnipet',
                  12: 'Wiki_Url',
                  13: 'Wiki_Name_Snipet',
                  14: 'Wiki_name_arrondissement',
                  15: 'Wiki_Coordinates_lat',
                  16: 'Wiki_Coordinates_lon',

                  17: 'W_Pays',
                  18: 'W_Region',
                  19: 'W_Departement',
                  20: 'W_Chef-lieu',
                  21: 'W_Code_arrondissement',
                  22: 'W_Population',
                  23: 'W_Densite',
                  24: 'W_Superficie',
                  25: 'W_Cantons',
                  26: 'W_Communes',

                  53: 'W_Name_ru',
                  54: 'W_Name_uk',
                  55: 'W_Name_en',
                  56: 'W_Name_de',
                  57: 'W_Name_pl',
                  58: 'W_Name_es',
                  59: 'W_Name_pt',
                  60: 'W_Name_it',
                  61: 'W_Name_nl',
                  62: 'W_Name_da',
                  63: 'W_Name_no',
                  64: 'W_Name_sv',
                  65: 'W_Name_cs',
                  66: 'W_Name_ro',
                  67: 'W_Name_bg',
                  68: 'W_Name_hu',
                  69: 'W_Name_sk',
                  70: 'W_Name_sl',
                  71: 'W_Name_sh',
                  72: 'W_Name_hr',
                  73: 'W_Url_ru',
                  74: 'W_Url_uk',
                  75: 'W_Url_en',
                  76: 'W_Url_de',
                  77: 'W_Url_pl',
                  78: 'W_Url_es',
                  79: 'W_Url_pt',
                  80: 'W_Url_it',
                  81: 'W_Url_nl',
                  82: 'W_Url_da',
                  83: 'W_Url_no',
                  84: 'W_Url_sv',
                  85: 'W_Url_cs',
                  86: 'W_Url_ro',
                  87: 'W_Url_bg',
                  88: 'W_Url_hu',
                  89: 'W_Url_sk',
                  90: 'W_Url_sl',
                  91: 'W_Url_sh',
                  92: 'W_Url_hr',
                  }

    DictHeader = collections.OrderedDict(sorted(DictHeader.items()))
    ListHeader = []
    for Header in DictHeader.values():
        ListHeader.append(Header)
    return Delimiter.join(ListHeader)


def GetHeader_Departements(Delimiter):
    DictHeader = {1: 'I_Code_departament',
                  2: 'I_Region',
                  3: 'I_Dep',
                  4: 'I_Chefleeu',
                  5: 'I_Tncc',
                  6: 'I_Ncc',
                  7: 'I_Nccenr',
                  12: 'Wiki_Url',
                  13: 'Wiki_Name_Snipet',
                  14: 'Wiki_name_departement',
                  17: 'W_Pays',
                  18: 'W_Region',
                  19: 'W_Creation_du_departementt',
                  20: 'W_Chef_lieu',
                  21: 'W_Sous_pefectures',
                  22: 'W_President_du_conseil_departemental',
                  23: 'W_Prefet',
                  24: 'W_Code_Insee',
                  25: 'W_Code_ISO_3166_2',
                  26: 'W_Code_Eurostat_NUTS_3',
                  27: 'W_Gentile',
                  28: 'W_Population',
                  29: 'W_Densite',
                  30: 'W_Superficie',
                  31: 'W_Arrondissements',
                  32: 'W_Circonscriptions_legislatives',
                  33: 'W_Cantons',
                  34: 'W_Intercommunalites',
                  35: 'W_Communes',
                  53: 'W_Name_ru',
                  54: 'W_Name_uk',
                  55: 'W_Name_en',
                  56: 'W_Name_de',
                  57: 'W_Name_pl',
                  58: 'W_Name_es',
                  59: 'W_Name_pt',
                  60: 'W_Name_it',
                  61: 'W_Name_nl',
                  62: 'W_Name_da',
                  63: 'W_Name_no',
                  64: 'W_Name_sv',
                  65: 'W_Name_cs',
                  66: 'W_Name_ro',
                  67: 'W_Name_bg',
                  68: 'W_Name_hu',
                  69: 'W_Name_sk',
                  70: 'W_Name_sl',
                  71: 'W_Name_sh',
                  72: 'W_Name_hr',
                  73: 'W_Url_ru',
                  74: 'W_Url_uk',
                  75: 'W_Url_en',
                  76: 'W_Url_de',
                  77: 'W_Url_pl',
                  78: 'W_Url_es',
                  79: 'W_Url_pt',
                  80: 'W_Url_it',
                  81: 'W_Url_nl',
                  82: 'W_Url_da',
                  83: 'W_Url_no',
                  84: 'W_Url_sv',
                  85: 'W_Url_cs',
                  86: 'W_Url_ro',
                  87: 'W_Url_bg',
                  88: 'W_Url_hu',
                  89: 'W_Url_sk',
                  90: 'W_Url_sl',
                  91: 'W_Url_sh',
                  92: 'W_Url_hr',
                  }

    DictHeader = collections.OrderedDict(sorted(DictHeader.items()))
    ListHeader = []
    for Header in DictHeader.values():
        ListHeader.append(Header)
    return Delimiter.join(ListHeader)

if __name__ == '__main__':
    print GetHeader_2('\n')