# -*- coding: utf-8 -*-
import re

mycode = '''
        InseeXls_CodeCommune = Data['InseeXls_CodeCommune']
        InseeXls_NameCommune = Data['InseeXls_NameCommune']
        InseeXls_Population = Data['InseeXls_Population']
        Wiki_Url = Data['Wiki_Url']
        W_Pays = Data['W_Pays']
        W_Region = Data['W_Region']
        W_Departement = Data['W_Departement']
        W_Arrondissement = Data['W_Arrondissement']
        W_Canton = Data['W_Canton']
        W_Intercommunalite = Data['W_Intercommunalite']
        W_CodePostal = Data['W_CodePostal']
        W_CodeCommune = Data['W_CodeCommune']
        W_Population = Data['W_Population']
        W_Densite = Data['W_Densite']
        W_Cordommees = Data['W_Cordommees']
        W_Altitude = Data['W_Altitude']
        W_Superficie = Data['W_Superficie']
        W_Name_ru = Data['W_Name_ru']
        W_Name_uk = Data['W_Name_uk']
        W_Name_en = Data['W_Name_en']
        W_Name_de = Data['W_Name_de']
        W_Name_pl = Data['W_Name_pl']
        W_Name_es = Data['W_Name_es']
        W_Name_pt = Data['W_Name_pt']
        W_Name_it = Data['W_Name_it']
        W_Name_nl = Data['W_Name_nl']
        W_Name_da = Data['W_Name_da']
        W_Name_no = Data['W_Name_no']
        W_Name_sv = Data['W_Name_sv']
        W_Name_cs = Data['W_Name_cs']
        W_Name_ro = Data['W_Name_ro']
        W_Name_bg = Data['W_Name_bg']
        W_Name_hu = Data['W_Name_hu']
        W_Name_sk = Data['W_Name_sk']
        W_Name_sl = Data['W_Name_sl']
        W_Name_sh = Data['W_Name_sh']
        W_Name_hr = Data['W_Name_hr']
        W_Url_ru = Data['W_Url_ru']
        W_Url_uk = Data['W_Url_uk']
        W_Url_en = Data['W_Url_en']
        W_Url_de = Data['W_Url_de']
        W_Url_pl = Data['W_Url_pl']
        W_Url_es = Data['W_Url_es']
        W_Url_pt = Data['W_Url_pt']
        W_Url_it = Data['W_Url_it']
        W_Url_nl = Data['W_Url_nl']
        W_Url_da = Data['W_Url_da']
        W_Url_no = Data['W_Url_no']
        W_Url_sv = Data['W_Url_sv']
        W_Url_cs = Data['W_Url_cs']
        W_Url_ro = Data['W_Url_ro']
        W_Url_bg = Data['W_Url_bg']
        W_Url_hu = Data['W_Url_hu']
        W_Url_sk = Data['W_Url_sk']
        W_Url_sl = Data['W_Url_sl']
        W_Url_sh = Data['W_Url_sh']
        W_Url_hr = Data['W_Url_hr']
        '''
DictMycode = {}
for i in mycode.split('\n'):
    d = i.replace('        ', '').replace(' ', '')
    print d,